version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: wanderLocal
      POSTGRES_USER: shu
      POSTGRES_PASSWORD: Lobster70!
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - postgres

volumes:
  postgres-data:
